### ISSUE TITLE
Hero alignment on homepage refresh

### ISSUE THREAD

**Issue by samajammin** [ethereum/fellowship-program-website#1]
**Describe the bug**

Initial load looks fine but when refreshing the browser, the alignment gets offset:
https://share.getcloudapp.com/wbuKZ5dW

**To Reproduce**

1. Go to https://fellowship.ethereum.foundation/
2. Refresh the page
3. See that page loads partially scrolled down

**Expected behavior**

Reloads should start user at top of page.

**Screenshots**

See video:
https://share.getcloudapp.com/wbuKZ5dW

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Brave

**Comment by corwintines** [comment]
Going to close this out with the redesign that is going out
