### ISSUE TITLE
Submission Form Error message unhelpful, salesforce integration failed

### ISSUE THREAD

**Issue by gichiba** [ethereum/fellowship-program-website#13]
We got a message to fellowship@ethereum.org that states: 

"I am not able to submit my application for the fellowship program. I get an error submitting, please try again message without identifying the error."

After checking the spreadsheet, we can see that the application was transmitted and received to Google docs, but not to Salesforce.

It's unclear what was causing the error, or how to reproduce it, but maybe it would be a good idea to add some more information to the error message that lets an applicant know they can reach out to fellowship@ethereum.org if they are worried their application was not submitted.

**Comment by samajammin** [comment]
Thanks for reporting @gichiba!

@nhsz how do we handle this on the ESP site? I believe we return the error from Salesforce to display on the client, which seems like a reasonable approach here but looking at the code I'm not seeing where/if we actually do that:
https://github.com/ethereum/esp-website/blob/master/src/pages/api/office-hours.ts#L57
