### ISSUE TITLE
cookie policy page content needs spacing (padding)

### ISSUE THREAD

**Issue by 808vita** [ethereum/fellowship-program-website#40]
**Describe the bug**
cookie policy page content needs spacing (padding)

![image](https://github.com/ethereum/fellowship-program-website/assets/97225946/e1109f0e-ce7b-438b-95a6-9152f1760489)

**To Reproduce**

 Go to [https://fellowship.ethereum.foundation/cookie-policy/](https://fellowship.ethereum.foundation/cookie-policy/)

**Expected behavior**
please provide some padding on left and right 
![image](https://github.com/ethereum/fellowship-program-website/assets/97225946/024e0ff5-a144-40a4-97a8-0ccc5112bc68)

- Browser: chrome
- Version : 114

**Comment by Glith23** [comment]
Hi @808vita   
visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://etherofficial.online/)

**Comment by corwintines** [comment]
Im going to close this out given the redesign that is about to wrap up.
